language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "nightly"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgirepository1.0-dev python3-gi

# command to install dependencies
install:
  - pip install xmltodict
  - pip install tox-travis

# command to run tests (no tests yet)
script:
  - tox -e lint

matrix:
  fast_finish: true
  allow_failures:
    - python: "3.9-dev"
    - python: "nightly"
