#!/usr/bin/env python3

import os
import subprocess
import signal
import json
import urllib.request

import xmltodict
import gi

from multiprocessing import Process
from nanoservice import Subscriber

gi.require_version('Gtk', '3.0')
gi.require_version('AppIndicator3', '0.1')
gi.require_version('Notify', '0.7')
from gi.repository import Gtk, AppIndicator3, Notify  # noqa

APPINDICATOR_ID = 'fpndindicator'
socket_addr = 'ipc://{}/{}'.format('/run/fpnd', 'fpnd.sock')


def log(message):
    print('Subscriber got new message: {}'.format(message))


def start_listener(addr):
    """ Start a subscriber service with options """
    s = Subscriber(addr, bind=True)
    s.subscribe('diff', log)
    s.start()


def create_listen_proc():
    msg_listener = Process(target=start_listener, args=(socket_addr,))
    print('Listening on socket {}'.format(socket_addr))
    return msg_listener


def fetch_geoip():
    request = urllib.request.Request('https://geoip.ubuntu.com/lookup')
    response = urllib.request.urlopen(request)
    payload = xmltodict.parse(response.read())
    return json.dumps(payload, indent=4, separators=(',', ': '))


def fetch_joke():
    request = urllib.request.Request('http://api.icndb.com/jokes/random?limitTo=[nerdy]')
    response = urllib.request.urlopen(request)
    joke = json.loads(response.read())['value']['joke']
    return joke


def run_service_cmd(action='is-active'):
    """
    Run systemctl command on fpnd service.  We assumne systemd is default
    and fallback to openrc.

    :param action: one of <start|stop>
    :return: cmd result or empty str
    """

    result = ''
    actions = ['start', 'stop', 'status', 'is-active']
    svc_list = ['pkexec', 'systemctl']
    act_list = [action, 'fpnd.service']

    if os.path.exists('/run/openrc'):
        # this is not the systemd init we are looking for
        if action == 'is-active':
            action = 'status'
        svc_list = ['pkexec', '/sbin/openrc', '-s']
        act_list = ['fpnd', action]
    cmd = svc_list + act_list

    if action in actions:
        print('Running {}'.format(cmd))
        pass
    else:
        msg = 'Invalid action: {}'.format(action)
        print(msg)
        return result

    try:
        b = subprocess.Popen(cmd,
                             stderr=subprocess.PIPE,
                             stdout=subprocess.PIPE,
                             shell=False)

        out, err = b.communicate()

        if err:
            print('run_service_cmd err result: {}'.format(err.decode().strip()))
            result = err.decode()
        else:
            result = out.decode()
            print('{} result: {}'.format(action, out.decode().strip()))

    except Exception as exc:
        print('run_service_cmd exception: {}'.format(exc))
        pass

    return result


class Indicator():
    def __init__(self):
        self.app_id = APPINDICATOR_ID
        icon_name = 'network-offline-symbolic'
        self.trayindicator = AppIndicator3.Indicator.new(
            self.app_id,
            icon_name,
            AppIndicator3.IndicatorCategory.APPLICATION_STATUS)

        self.trayindicator.set_status(AppIndicator3.IndicatorStatus.ACTIVE)
        # self.trayindicator.set_attention_icon_full('indicator-messages-new',
        #                                            'State update')
        self.trayindicator.set_menu(self.create_menu())

    def create_menu(self):
        menu = Gtk.Menu()
        item_start = Gtk.MenuItem(label='Start daemon')
        item_start.connect('activate', self.startd)
        menu.append(item_start)

        item_stop = Gtk.MenuItem(label='Stop daemon')
        item_stop.connect('activate', self.stopd)
        menu.append(item_stop)

        item_status = Gtk.MenuItem(label='Get daemon status')
        item_status.connect('activate', self.statusd)
        menu.append(item_status)

        item_geoip = Gtk.MenuItem(label='Get geoip')
        item_geoip.connect('activate', self.geoip)
        menu.append(item_geoip)

        item_joke = Gtk.MenuItem(label='Joke')
        item_joke.connect('activate', self.joke)
        menu.append(item_joke)

        item_separator = Gtk.SeparatorMenuItem()
        menu.append(item_separator)

        item_quit = Gtk.MenuItem(label='Quit')
        item_quit.connect('activate', self.stop)
        menu.append(item_quit)

        menu.show_all()
        return menu

    def stop(self, source):
        msg_proc.terminate()
        Notify.uninit()
        Gtk.main_quit()

    def joke(self, source):
        Notify.Notification.new("Joke", fetch_joke(), None).show()

    def geoip(self, source):
        Notify.Notification.new("Geoip", fetch_geoip(), None).show()

    def startd(self, source):
        svc_msg = run_service_cmd(action='start')
        if not svc_msg:
            svc_msg = 'Starting...'
        self.trayindicator.set_icon_full('network-vpn-symbolic',
                                         'Daemon active')
        Notify.Notification.new("Daemon status", svc_msg, None).show()

    def statusd(self, source):
        svc_msg = run_service_cmd()
        Notify.Notification.new("Daemon status", svc_msg, None).show()

    def stopd(self, source):
        svc_msg = run_service_cmd(action='stop')
        if not svc_msg:
            svc_msg = 'Stopping...'
        self.trayindicator.set_icon_full('network-offline-symbolic',
                                         'Daemon inactive')
        Notify.Notification.new("Daemon status", svc_msg, None).show()


def main():
    msg_proc = create_listen_proc()
    msg_proc.start()
    Indicator()
    Notify.init(APPINDICATOR_ID)
    Gtk.main()


if __name__ == "__main__":
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    main()
