.TH freepn-gtk3-indicator 1 2020-06-26 "" ""
.SH NAME
freepn-gtk3-indicator \- Freepn daemon control and status indicator.
.SH SYNOPSIS
.BR freepn-gtk3-indicator " (no options)"
.SH DESCRIPTION
.B freepn-gtk3-indicator
is a daemon control and status application for fpnd on Linux. It shows an
icon in the indicator area or the system tray (whatever is available in
your desktop environment). The icon's menu allows you to start and stop
the daemon, as well as get daemon status and query the Ubuntu geoip
location server.

This application would normally start automatically after logging in, but can
also be run manually from the command line for some debug output.
.SH AUTHOR
Stephen L Arnold (nerdboy@gentoo.org)
